language: python
dist: xenial
python:
- '3.6'
- '3.7'
install:
- pip install codecov
- pip install -r requirements.txt
- pip install -r test_requirements.txt
env:
  global:
    secure: IqqOX+CQs9/BfSFbASse2OWLKsAF1PDlHWmeK1BSVjf1TfPeESoDJYYgv6dvegZqwKzguyiqIQ8F1x/98YYqz3zEKGV9e0gJfMnutdZHY6qB1racoHoo+jZOFLolZcLI1P6SODlikySC45AtQSyc1DhrnQLDuV+iDrkaZPWYfR6BbKR+mUUGPUAoKR+BXgly47PjC4YUjkcjZ/gLjhQnAC3YiLuY8KV0lAM0EIO3AvtW/KrNQoYdNBYKKK+CTbyxelevh4xTNEuiikueY+1qFQgaOdk3vO72FEepC2i6l2Wu5t4sGibrTO6e+pLwrXspKEGOZyjQ7Mh7B8YrAArZdbgSo3s9iXR+oGrtTZLxm7JTHeqDDHI03vY/Qo6TbzLYhX9X4GEIPxSpMrpqU9LhPpeXT1GRYQpAkvlMaLHKGZGq8AOxiLu4g8PUR6jjlX+ovT/wvC7Xa3FzHc8fTRPBygq8T1W5fKLqYVDyMe++4pSqAgP1Bnn2IaJ2b132oTKZ6ByYZZkSy87XOSDJcz2CXXt39CkK3wZw1IYoOC0ybMQbPMD1RxLTDAMx5aDb2pE13pjvQeVbjpgMP4eRuCD4qpxlppJPHcZe/JPp0HUldXmEhuwH0DxxAYZulMBnctmI+8zAguk4is9Ct9b0PEBzpgrEWWCOegRILaEACaPsuwo=
script:
- python setup.py test
cache:
- pip
after_success:
- codecov -t 27ef6fc2-7ebc-4ff5-94c9-58c0c10f26c0
jobs:
  include:
    if: branch = develop
    stage: push
    install: skip
    script: skip
    after_success:
    - codecov -t 27ef6fc2-7ebc-4ff5-94c9-58c0c10f26c0
    - chmod +x .travis/merge_script.sh
    - BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=AllenInstitute/em_coregistration
      .travis/merge_script.sh
