language: python
dist: xenial
python:
- '3.6'
- '3.7'
install:
- pip install codecov
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- python setup.py test
cache:
- pip
jobs:
  include:
    if: branch = develop
    stage: push
    install: skip
    script: skip
    after_success:
    - chmod +x .travis/merge_script.sh
    - BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=AllenInstitute/em_coregistration
      .travis/merge_script.sh
