language: python
dist: xenial
python:
- '3.6'
- '3.7'
install:
- pip install codecov
- pip install -r requirements.txt
- pip install -r test_requirements.txt
env:
  global:
    secure: a0eW5cv2aSVLqJPmnY4c8sj7SGb1xTnrAJuYlLavSERbpkjHQzIIndhmv9xN0iaua21Bd28HK/qPALgIA2wiGECWhU4kM7zCl/Uy4YCEuXSQgHWwBfn85XggqhQLuHfp24G5XilpiNgvbDhoL6YKUEjKvDHQmEZoc7+ybRtKgxITakyuPY1Sr3Syzi3f6CfyB+ATuwqz49RobmRRPUqHDDS2Gg1sVS7jrZr/fZDIYBKNjLMLrnuni3LRNyNbgNBu30F21k5kBPuU183wUn6ya013Unid9JR209g5NCNbsVDtKSokqVCUidmmfrCoIBKntrLw7oA/UAJO8TiUGHcoZCFcLfT7v7t4jmo9NOmjjD4fQv9GwMXoReZAPogqgj5iKN5cN4KEAiETCM29BdjlMQ0ds/8yzuWAuQSLMYK+HizVoCBxzu2aeyHPsKI13YKPuz9byUBK2NylelWWs2GhDumoMoVY1yD9hr/BIkNstytwyLBf6DeKtHA8HdVDjkMVbGCeSF3LwxzISeOneFYzMP0P09+MePrM+UsQSCwXN8SHLfagpjvby0tFMrMkhKIAvO6HY0OhyfA8MDix/Y/yj1qgqtyjiHGfJzevo5KNHHM8b7igwchB9k0WwOGwJ5GZDKxtnatAlt87FmVFjWwEB6axAcdt7Q+k7UGWHSw6bSU=
script:
- python setup.py test
cache:
- pip
after_success:
- codecov -t 27ef6fc2-7ebc-4ff5-94c9-58c0c10f26c0
jobs:
  include:
    if: branch = develop
    stage: push
    install: skip
    script: skip
    after_success:
    - codecov -t 27ef6fc2-7ebc-4ff5-94c9-58c0c10f26c0
    - chmod +x .travis/merge_script.sh
    - BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=AllenInstitute/em_coregistration
      .travis/merge_script.sh
